import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class PaymentNoticeTC {

	@Test
	void test() {
		
		String paymentNoticePayload = 
				"{\r\n"
				+ "    \"resourceType\": \"Bundle\",\r\n"
				+ "    \"id\": \"e4b9cb03-e3a6-4c19-ae3d-6501e97e7889\",\r\n"
				+ "    \"meta\": {\r\n"
				+ "        \"profile\": [\r\n"
				+ "            \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/bundle|1.0.0\"\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"type\": \"message\",\r\n"
				+ "    \"timestamp\": \"2022-07-24T04:10:25.843+00:00\",\r\n"
				+ "    \"entry\": [\r\n"
				+ "        {\r\n"
				+ "            \"fullUrl\": \"urn:uuid:3e9667f3-de8b-4110-80b9-80cfd1454cf1\",\r\n"
				+ "            \"resource\": {\r\n"
				+ "                \"resourceType\": \"MessageHeader\",\r\n"
				+ "                \"id\": \"3e9667f3-de8b-4110-80b9-80cfd1454cf1\",\r\n"
				+ "                \"meta\": {\r\n"
				+ "                    \"profile\": [\r\n"
				+ "                        \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/message-header|1.0.0\"\r\n"
				+ "                    ]\r\n"
				+ "                },\r\n"
				+ "                \"eventCoding\": {\r\n"
				+ "                    \"system\": \"http://nphies.sa/terminology/CodeSystem/ksa-message-events\",\r\n"
				+ "                    \"code\": \"payment-notice\"\r\n"
				+ "                },\r\n"
				+ "                \"destination\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"endpoint\": \"http://nphies.sa\",\r\n"
				+ "                        \"receiver\": {\r\n"
				+ "                            \"type\": \"Organization\",\r\n"
				+ "                            \"identifier\": {\r\n"
				+ "                                \"system\": \"http://nphies.sa/license/nphies\",\r\n"
				+ "                                \"value\": \"NPHIES\"\r\n"
				+ "                            }\r\n"
				+ "                        }\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"sender\": {\r\n"
				+ "                    \"type\": \"Organization\",\r\n"
				+ "                    \"identifier\": {\r\n"
				+ "                        \"system\": \"http://nphies.sa/license/provider-license\",\r\n"
				+ "                        \"value\": \"PR-FHIR\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                \"source\": {\r\n"
				+ "                    \"endpoint\": \"http://nphies.sa/license/provider-license/PR-FHIR\"\r\n"
				+ "                },\r\n"
				+ "                \"focus\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"reference\": \"http://Provider_BaseURL.com.sa/PaymentNotice/182577\"\r\n"
				+ "                    }\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fullUrl\": \"http://Provider_BaseURL.com.sa/PaymentNotice/182577\",\r\n"
				+ "            \"resource\": {\r\n"
				+ "                \"resourceType\": \"PaymentNotice\",\r\n"
				+ "                \"id\": \"182577\",\r\n"
				+ "                \"meta\": {\r\n"
				+ "                    \"profile\": [\r\n"
				+ "                        \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/payment-notice|1.0.0\"\r\n"
				+ "                    ]\r\n"
				+ "                },\r\n"
				+ "                \"identifier\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"system\": \"http://Provider_BaseURL.com.sa/paymentnotice\",\r\n"
				+ "                        \"value\": \"579122\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"status\": \"active\",\r\n"
				+ "                \"created\": \"2022-07-24T04:10:25.843Z\",\r\n"
				+ "                \"provider\": {\r\n"
				+ "                    \"reference\": \"http://Provider_BaseURL.com.sa/Organization/10\"\r\n"
				+ "                },\r\n"
				+ "                \"payment\": {\r\n"
				+ "                    \"identifier\": {\r\n"
				+ "                        \"system\": \"http://pseudo-payer.com.sa/paymentreconciliation\",\r\n"
				+ "                        \"value\": \"258426\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                \"paymentDate\": \"2022-07-24\",\r\n"
				+ "                \"payee\": {\r\n"
				+ "                    \"reference\": \"http://Provider_BaseURL.com.sa/Organization/10\"\r\n"
				+ "                },\r\n"
				+ "                \"recipient\": {\r\n"
				+ "                    \"identifier\": {\r\n"
				+ "                        \"system\": \"http://nphies.sa/license/nphies\",\r\n"
				+ "                        \"value\": \"NPHIES\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                \"amount\": {\r\n"
				+ "                    \"value\": 968,\r\n"
				+ "                    \"currency\": \"SAR\"\r\n"
				+ "                },\r\n"
				+ "                \"paymentStatus\": {\r\n"
				+ "                    \"coding\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"system\": \"http://terminology.hl7.org/CodeSystem/paymentstatus\",\r\n"
				+ "                            \"code\": \"cleared\"\r\n"
				+ "                        }\r\n"
				+ "                    ]\r\n"
				+ "                }\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fullUrl\": \"http://Provider_BaseURL.com.sa/Organization/10\",\r\n"
				+ "            \"resource\": {\r\n"
				+ "                \"resourceType\": \"Organization\",\r\n"
				+ "                \"id\": \"10\",\r\n"
				+ "                \"meta\": {\r\n"
				+ "                    \"profile\": [\r\n"
				+ "                        \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/provider-organization|1.0.0\"\r\n"
				+ "                    ]\r\n"
				+ "                },\r\n"
				+ "                \"identifier\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"system\": \"http://nphies.sa/license/provider-license\",\r\n"
				+ "                        \"value\": \"PR-FHIR\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"active\": true,\r\n"
				+ "                \"type\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"coding\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"system\": \"http://nphies.sa/terminology/CodeSystem/organization-type\",\r\n"
				+ "                                \"code\": \"prov\"\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"name\": \"Saudi General Hospital\"\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
	
	}

}
