import io.restassured.RestAssured;
import io.restassured.config.EncoderConfig;
import io.restassured.response.Response;

import static io.restassured.RestAssured.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;


public class Project {
	
	public static String payload = 
			"{\r\n"
			+ "	\"resourceType\": \"Bundle\",\r\n"
			+ "	\"id\": \"83bdc704-d2ff-4762-bf69-d73522f15cf3\",\r\n"
			+ "	\"meta\": {\r\n"
			+ "		\"profile\": [\r\n"
			+ "			\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/bundle|1.0.0\"\r\n"
			+ "		]\r\n"
			+ "	},\r\n"
			+ "	\"type\": \"message\",\r\n"
			+ "	\"timestamp\": \"2022-07-24T22:11:20.762Z\",\r\n"
			+ "	\"entry\": [\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/MessageHeader/4c117c32-a044-44e4-bb14-33411bdccb7e\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"MessageHeader\",\r\n"
			+ "				\"id\": \"4c117c32-a044-44e4-bb14-33411bdccb7e\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/message-header|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"eventCoding\": {\r\n"
			+ "					\"system\": \"http://nphies.sa/terminology/CodeSystem/ksa-message-events\",\r\n"
			+ "					\"code\": \"claim-request\"\r\n"
			+ "				},\r\n"
			+ "				\"destination\": [\r\n"
			+ "					{\r\n"
			+ "						\"endpoint\": \"http://nphies.sa/license/payer-license/INS-FHIR\",\r\n"
			+ "						\"receiver\": {\r\n"
			+ "							\"type\": \"Organization\",\r\n"
			+ "							\"identifier\": {\r\n"
			+ "								\"system\": \"http://nphies.sa/license/payer-license\",\r\n"
			+ "								\"value\": \"INS-FHIR\"\r\n"
			+ "							}\r\n"
			+ "						}\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"sender\": {\r\n"
			+ "					\"type\": \"Organization\",\r\n"
			+ "					\"identifier\": {\r\n"
			+ "						\"system\": \"http://nphies.sa/license/provider-license\",\r\n"
			+ "						\"value\": \"PR-FHIR\"\r\n"
			+ "					}\r\n"
			+ "				},\r\n"
			+ "				\"source\": {\r\n"
			+ "					\"endpoint\": \"http://nphies.sa/license/provider-license/PR-FHIR\"\r\n"
			+ "				},\r\n"
			+ "				\"focus\": [\r\n"
			+ "					{\r\n"
			+ "						\"reference\": \"http://Provider_BaseURL.com.sa/Claim/525432\"\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Claim/525432\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Claim\",\r\n"
			+ "				\"id\": \"525432\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/oral-claim|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"extension\": [\r\n"
			+ "					{\r\n"
			+ "						\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-authorization-offline-date\",\r\n"
			+ "						\"valueDateTime\": \"2021-06-30T11:05:48+03:00\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"system\": \"http://Provider_BaseURL.com.sa/claim\",\r\n"
			+ "						\"value\": \"835289\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"status\": \"active\",\r\n"
			+ "				\"type\": {\r\n"
			+ "					\"coding\": [\r\n"
			+ "						{\r\n"
			+ "							\"system\": \"http://terminology.hl7.org/CodeSystem/claim-type\",\r\n"
			+ "							\"code\": \"oral\"\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"use\": \"claim\",\r\n"
			+ "				\"patient\": {\r\n"
			+ "					\"reference\": \"http://Provider_BaseURL.com.sa/Patient/30\"\r\n"
			+ "				},\r\n"
			+ "				\"created\": \"2022-07-24T22:11:20.762Z\",\r\n"
			+ "				\"insurer\": {\r\n"
			+ "					\"reference\": \"http://Provider_BaseURL.com.sa/Organization/60\"\r\n"
			+ "				},\r\n"
			+ "				\"provider\": {\r\n"
			+ "					\"reference\": \"http://Provider_BaseURL.com.sa/Organization/50\"\r\n"
			+ "				},\r\n"
			+ "				\"priority\": {\r\n"
			+ "					\"coding\": [\r\n"
			+ "						{\r\n"
			+ "							\"system\": \"http://terminology.hl7.org/CodeSystem/processpriority\",\r\n"
			+ "							\"code\": \"normal\"\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"payee\": {\r\n"
			+ "					\"type\": {\r\n"
			+ "						\"coding\": [\r\n"
			+ "							{\r\n"
			+ "								\"system\": \"http://terminology.hl7.org/CodeSystem/payeetype\",\r\n"
			+ "								\"code\": \"provider\"\r\n"
			+ "							}\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				},\r\n"
			+ "				\"careTeam\": [\r\n"
			+ "					{\r\n"
			+ "						\"sequence\": 1,\r\n"
			+ "						\"provider\": {\r\n"
			+ "							\"reference\": \"http://Provider_BaseURL.com.sa/Practitioner/70\"\r\n"
			+ "						},\r\n"
			+ "						\"role\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://terminology.hl7.org/CodeSystem/claimcareteamrole\",\r\n"
			+ "									\"code\": \"primary\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"qualification\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/practice-codes\",\r\n"
			+ "									\"code\": \"22.00\",\r\n"
			+ "									\"display\": \"Dental\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						}\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"diagnosis\": [\r\n"
			+ "					{\r\n"
			+ "						\"sequence\": 1,\r\n"
			+ "						\"diagnosisCodeableConcept\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://hl7.org/fhir/sid/icd-10-am\",\r\n"
			+ "									\"code\": \"K02.5\",\r\n"
			+ "									\"display\": \"Caries with pulp exposure\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"type\": [\r\n"
			+ "							{\r\n"
			+ "								\"coding\": [\r\n"
			+ "									{\r\n"
			+ "										\"system\": \"http://nphies.sa/terminology/CodeSystem/diagnosis-type\",\r\n"
			+ "										\"code\": \"differential\"\r\n"
			+ "									}\r\n"
			+ "								]\r\n"
			+ "							}\r\n"
			+ "						]\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"sequence\": 2,\r\n"
			+ "						\"diagnosisCodeableConcept\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://hl7.org/fhir/sid/icd-10-am\",\r\n"
			+ "									\"code\": \"K02.9\",\r\n"
			+ "									\"display\": \"Dental caries, unspecified\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"type\": [\r\n"
			+ "							{\r\n"
			+ "								\"coding\": [\r\n"
			+ "									{\r\n"
			+ "										\"system\": \"http://nphies.sa/terminology/CodeSystem/diagnosis-type\",\r\n"
			+ "										\"code\": \"principal\"\r\n"
			+ "									}\r\n"
			+ "								]\r\n"
			+ "							}\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"insurance\": [\r\n"
			+ "					{\r\n"
			+ "						\"sequence\": 1,\r\n"
			+ "						\"focal\": true,\r\n"
			+ "						\"coverage\": {\r\n"
			+ "							\"reference\": \"http://Provider_BaseURL.com.sa/Coverage/1\"\r\n"
			+ "						},\r\n"
			+ "						\"preAuthRef\": [\r\n"
			+ "							\"Pseudo-payer-Portal-Auth-01\"\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"item\": [\r\n"
			+ "					{\r\n"
			+ "						\"extension\": [\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-patient-share\",\r\n"
			+ "								\"valueMoney\": {\r\n"
			+ "									\"value\": 0,\r\n"
			+ "									\"currency\": \"SAR\"\r\n"
			+ "								}\r\n"
			+ "							},\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-package\",\r\n"
			+ "								\"valueBoolean\": false\r\n"
			+ "							},\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-tax\",\r\n"
			+ "								\"valueMoney\": {\r\n"
			+ "									\"value\": 0,\r\n"
			+ "									\"currency\": \"SAR\"\r\n"
			+ "								}\r\n"
			+ "							}\r\n"
			+ "						],\r\n"
			+ "						\"sequence\": 1,\r\n"
			+ "						\"careTeamSequence\": [\r\n"
			+ "							1\r\n"
			+ "						],\r\n"
			+ "						\"diagnosisSequence\": [\r\n"
			+ "							2\r\n"
			+ "						],\r\n"
			+ "						\"productOrService\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/oral-health-op\",\r\n"
			+ "									\"code\": \"532\",\r\n"
			+ "									\"display\": \"Direct restoration, using an adhesive technique and a tooth-coloured material, involving two surfaces of a posterior tooth.\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"servicedDate\": \"2022-07-24\",\r\n"
			+ "						\"quantity\": {\r\n"
			+ "							\"value\": 1\r\n"
			+ "						},\r\n"
			+ "						\"unitPrice\": {\r\n"
			+ "							\"value\": 500,\r\n"
			+ "							\"currency\": \"SAR\"\r\n"
			+ "						},\r\n"
			+ "						\"net\": {\r\n"
			+ "							\"value\": 500,\r\n"
			+ "							\"currency\": \"SAR\"\r\n"
			+ "						},\r\n"
			+ "						\"bodySite\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/fdi-oral-region\",\r\n"
			+ "									\"code\": \"27\",\r\n"
			+ "									\"display\": \"UPPER LEFT; PERMANENT TEETH # 7\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						}\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"extension\": [\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-tax\",\r\n"
			+ "								\"valueMoney\": {\r\n"
			+ "									\"value\": 0,\r\n"
			+ "									\"currency\": \"SAR\"\r\n"
			+ "								}\r\n"
			+ "							},\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-patient-share\",\r\n"
			+ "								\"valueMoney\": {\r\n"
			+ "									\"value\": 100,\r\n"
			+ "									\"currency\": \"SAR\"\r\n"
			+ "								}\r\n"
			+ "							},\r\n"
			+ "							{\r\n"
			+ "								\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-package\",\r\n"
			+ "								\"valueBoolean\": false\r\n"
			+ "							}\r\n"
			+ "						],\r\n"
			+ "						\"sequence\": 2,\r\n"
			+ "						\"careTeamSequence\": [\r\n"
			+ "							1\r\n"
			+ "						],\r\n"
			+ "						\"diagnosisSequence\": [\r\n"
			+ "							1\r\n"
			+ "						],\r\n"
			+ "						\"productOrService\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/oral-health-op\",\r\n"
			+ "									\"code\": \"458\",\r\n"
			+ "									\"display\": \"Interim therapeutic root filling   per tooth\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"servicedDate\": \"2022-07-24\",\r\n"
			+ "						\"quantity\": {\r\n"
			+ "							\"value\": 1\r\n"
			+ "						},\r\n"
			+ "						\"unitPrice\": {\r\n"
			+ "							\"value\": 500,\r\n"
			+ "							\"currency\": \"SAR\"\r\n"
			+ "						},\r\n"
			+ "						\"net\": {\r\n"
			+ "							\"value\": 500,\r\n"
			+ "							\"currency\": \"SAR\"\r\n"
			+ "						},\r\n"
			+ "						\"bodySite\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/fdi-oral-region\",\r\n"
			+ "									\"code\": \"24\",\r\n"
			+ "									\"display\": \"UPPER LEFT; PERMANENT TEETH # 4\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						}\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"total\": {\r\n"
			+ "					\"value\": 1000,\r\n"
			+ "					\"currency\": \"SAR\"\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Organization/50\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Organization\",\r\n"
			+ "				\"id\": \"50\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/provider-organization|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"system\": \"http://nphies.sa/license/provider-license\",\r\n"
			+ "						\"value\": \"PR-FHIR\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"active\": true,\r\n"
			+ "				\"type\": [\r\n"
			+ "					{\r\n"
			+ "						\"coding\": [\r\n"
			+ "							{\r\n"
			+ "								\"system\": \"http://nphies.sa/terminology/CodeSystem/organization-type\",\r\n"
			+ "								\"code\": \"prov\"\r\n"
			+ "							}\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Patient/30\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Patient\",\r\n"
			+ "				\"id\": \"30\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/patient|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://terminology.hl7.org/CodeSystem/v2-0203\",\r\n"
			+ "									\"code\": \"PRC\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"system\": \"http://nphies.sa/identifier/iqama\",\r\n"
			+ "						\"value\": \"3000000003\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"active\": true,\r\n"
			+ "				\"name\": [\r\n"
			+ "					{\r\n"
			+ "						\"use\": \"official\",\r\n"
			+ "						\"text\": \"Test Member - health Check\",\r\n"
			+ "						\"family\": \"Test Member - health Check\",\r\n"
			+ "						\"given\": [\r\n"
			+ "							\"Test Member - health Check\",\r\n"
			+ "							\"Test Member - health Check\"\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"telecom\": [\r\n"
			+ "					{\r\n"
			+ "						\"system\": \"phone\",\r\n"
			+ "						\"value\": \"0123456789\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"gender\": \"female\",\r\n"
			+ "				\"_gender\": {\r\n"
			+ "					\"extension\": [\r\n"
			+ "						{\r\n"
			+ "							\"url\": \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/extension-ksa-administrative-gender\",\r\n"
			+ "							\"valueCodeableConcept\": {\r\n"
			+ "								\"coding\": [\r\n"
			+ "									{\r\n"
			+ "										\"system\": \"http://nphies.sa/terminology/CodeSystem/ksa-administrative-gender\",\r\n"
			+ "										\"code\": \"female\"\r\n"
			+ "									}\r\n"
			+ "								]\r\n"
			+ "							}\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"birthDate\": \"2004-02-24\",\r\n"
			+ "				\"deceasedBoolean\": false,\r\n"
			+ "				\"address\": [\r\n"
			+ "					{\r\n"
			+ "						\"use\": \"home\",\r\n"
			+ "						\"line\": [\r\n"
			+ "							\"Olaya Street\"\r\n"
			+ "						],\r\n"
			+ "						\"text\": \" Olaya Street, Riyadh, KSA\",\r\n"
			+ "						\"city\": \"Riyadh\",\r\n"
			+ "						\"country\": \"Saudi Arabia\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"maritalStatus\": {\r\n"
			+ "					\"coding\": [\r\n"
			+ "						{\r\n"
			+ "							\"system\": \"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus\",\r\n"
			+ "							\"code\": \"U\"\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Organization/60\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Organization\",\r\n"
			+ "				\"id\": \"60\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/insurer-organization|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"system\": \"http://nphies.sa/license/payer-license\",\r\n"
			+ "						\"value\": \"INS-FHIR\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"active\": true,\r\n"
			+ "				\"type\": [\r\n"
			+ "					{\r\n"
			+ "						\"coding\": [\r\n"
			+ "							{\r\n"
			+ "								\"system\": \"http://nphies.sa/terminology/CodeSystem/organization-type\",\r\n"
			+ "								\"code\": \"ins\"\r\n"
			+ "							}\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Coverage/1\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Coverage\",\r\n"
			+ "				\"id\": \"1\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/coverage|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"system\": \"http://pseudo-payer.com.sa/memberid\",\r\n"
			+ "						\"value\": \"Test Member - health Check\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"status\": \"active\",\r\n"
			+ "				\"type\": {\r\n"
			+ "					\"coding\": [\r\n"
			+ "						{\r\n"
			+ "							\"system\": \"http://nphies.sa/terminology/CodeSystem/coverage-type\",\r\n"
			+ "							\"code\": \"EHCPOL\"\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"subscriber\": {\r\n"
			+ "					\"reference\": \"http://Provider_BaseURL.com.sa/Patient/30\"\r\n"
			+ "				},\r\n"
			+ "				\"subscriberId\": \"Test Member - health Check\",\r\n"
			+ "				\"beneficiary\": {\r\n"
			+ "					\"reference\": \"http://Provider_BaseURL.com.sa/Patient/30\"\r\n"
			+ "				},\r\n"
			+ "				\"dependent\": \"Test Member - health Check\",\r\n"
			+ "				\"relationship\": {\r\n"
			+ "					\"coding\": [\r\n"
			+ "						{\r\n"
			+ "							\"system\": \"http://terminology.hl7.org/CodeSystem/subscriber-relationship\",\r\n"
			+ "							\"code\": \"self\"\r\n"
			+ "						}\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"period\": {\r\n"
			+ "					\"start\": \"2021-01-01\",\r\n"
			+ "					\"end\": \"2022-01-01\"\r\n"
			+ "				},\r\n"
			+ "				\"payor\": [\r\n"
			+ "					{\r\n"
			+ "						\"reference\": \"http://Provider_BaseURL.com.sa/Organization/60\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"class\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://terminology.hl7.org/CodeSystem/coverage-class\",\r\n"
			+ "									\"code\": \"class\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"value\": \"Test Member - health Check\",\r\n"
			+ "						\"name\": \"Test Member - health Check\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"network\": \"Test Member - health Check\",\r\n"
			+ "				\"costToBeneficiary\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://nphies.sa/terminology/CodeSystem/coverage-copay-type\",\r\n"
			+ "									\"code\": \"copay\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"valueMoney\": {\r\n"
			+ "							\"value\": 50,\r\n"
			+ "							\"currency\": \"SAR\"\r\n"
			+ "						}\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"subrogation\": true\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"fullUrl\": \"http://Provider_BaseURL.com.sa/Practitioner/70\",\r\n"
			+ "			\"resource\": {\r\n"
			+ "				\"resourceType\": \"Practitioner\",\r\n"
			+ "				\"id\": \"70\",\r\n"
			+ "				\"meta\": {\r\n"
			+ "					\"profile\": [\r\n"
			+ "						\"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/practitioner|1.0.0\"\r\n"
			+ "					]\r\n"
			+ "				},\r\n"
			+ "				\"identifier\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": {\r\n"
			+ "							\"coding\": [\r\n"
			+ "								{\r\n"
			+ "									\"system\": \"http://terminology.hl7.org/CodeSystem/v2-0203\",\r\n"
			+ "									\"code\": \"MD\"\r\n"
			+ "								}\r\n"
			+ "							]\r\n"
			+ "						},\r\n"
			+ "						\"system\": \"http://nphies.sa/license/practitioner-license\",\r\n"
			+ "						\"value\": \"Test practitioner for Health Check\"\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"active\": true,\r\n"
			+ "				\"name\": [\r\n"
			+ "					{\r\n"
			+ "						\"use\": \"official\",\r\n"
			+ "						\"text\": \"Test practitioner for Health Check\",\r\n"
			+ "						\"family\": \"Test practitioner for Health Check\",\r\n"
			+ "						\"given\": [\r\n"
			+ "							\"Test practitioner for Health Check\",\r\n"
			+ "							\"Test practitioner for Health Check\"\r\n"
			+ "						]\r\n"
			+ "					}\r\n"
			+ "				],\r\n"
			+ "				\"gender\": \"male\"\r\n"
			+ "			}\r\n"
			+ "		}\r\n"
			+ "		{\r\n"
			+ "            \"fullUrl\": \"http://sgh.com.sa/Location/2be1133308ed422a9923931c5a475f63\",\r\n"
			+ "            \"resource\": {\r\n"
			+ "                \"resourceType\": \"Location\",\r\n"
			+ "                \"id\": \"2be1133308ed422a9923931c5a475f63\",\r\n"
			+ "                \"meta\": {\r\n"
			+ "                    \"profile\": [\r\n"
			+ "                        \"http://nphies.sa/fhir/ksa/nphies-fs/StructureDefinition/location|1.0.0\"\r\n"
			+ "                    ]\r\n"
			+ "                },\r\n"
			+ "                \"identifier\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"system\": \"http://nphies.sa/license/location-license\",\r\n"
			+ "                        \"value\": \"GACH\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"status\": \"active\",\r\n"
			+ "                \"name\": \"Saudi General Hospital\",\r\n"
			+ "                \"type\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"coding\": [\r\n"
			+ "                            {\r\n"
			+ "                                \"system\": \"http://terminology.hl7.org/CodeSystem/v3-RoleCode\",\r\n"
			+ "                                \"code\": \"GACH\"\r\n"
			+ "                            }\r\n"
			+ "                        ]\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"managingOrganization\": {\r\n"
			+ "                    \"reference\": \"http://sgh.com.sa/Organization/b1b3432921324f97af3be9fd0b1a14ae\"\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "	]\r\n"
			+ "}";
	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		RestAssured.config = config().encoderConfig(EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false));
		
		RestAssured.baseURI = "http://hsb.oba.nphies.sa";
		Response response = given()
				.contentType("application/fhir+json")
				.header("Username", "Provider2")
				.header("Password", "P@ssw0rd")
				.body(payload)
				.when().post("$process-message")
				.then().log().all()
				.extract()
				.response();
				
				
        Assertions.assertEquals(200, response.statusCode());
        Assertions.assertEquals(200, response.jsonPath().getString(""));
		
	}
}
